# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 20:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escuelas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('realizada', models.BooleanField(default=False)),
                ('comentarios', models.TextField(default=None)),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuelas.Escuela')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Acciones',
                'verbose_name': 'Accion',
            },
        ),
    ]
