# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acciones', '0002_auto_20170122_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accion',
            old_name='comentarios',
            new_name='observaciones',
        ),
        migrations.AddField(
            model_name='accion',
            name='programada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accion',
            name='realizada',
            field=models.BooleanField(default=True),
        ),
    ]
