# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0003_auto_20170127_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='n_m',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
