# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0004_dispositivo_n_m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='n_s',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
