# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0005_auto_20170203_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='n_m',
            field=models.IntegerField(null=True),
        ),
    ]
