# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0002_auto_20170221_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escuela',
            name='directivo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='tel_directivo',
            field=models.CharField(max_length=50),
        ),
    ]
