# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escuelas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escuela', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='escuelas.Escuela')),
            ],
            options={
                'verbose_name_plural': 'Adms',
                'verbose_name': 'Adm',
            },
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField()),
                ('estado', models.IntegerField()),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('n_s', models.CharField(max_length=50)),
                ('adm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dispositivos.Adm')),
            ],
            options={
                'verbose_name_plural': 'Dispositivos',
                'verbose_name': 'Dispositivo',
            },
        ),
    ]
