# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0006_auto_20170205_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='estado',
            field=models.IntegerField(default=1),
        ),
    ]
